"""create Video model

Revision ID: 240a7d431558
Revises: c6ae8cd17929
Create Date: 2023-03-09 00:07:26.902376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240a7d431558'
down_revision = 'c6ae8cd17929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_filename'), 'videos', ['filename'], unique=False)
    op.create_index(op.f('ix_videos_filepath'), 'videos', ['filepath'], unique=False)
    op.create_index(op.f('ix_videos_filesize'), 'videos', ['filesize'], unique=False)
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_filesize'), table_name='videos')
    op.drop_index(op.f('ix_videos_filepath'), table_name='videos')
    op.drop_index(op.f('ix_videos_filename'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
